-- Inserindo registos na tabela agencia
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,1,'Agência número 1 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,2,'Agência número 2 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,3,'Agência número 3 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,4,'Agência número 4 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,5,'Agência número 5 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,6,'Agência número 6 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,7,'Agência número 7 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,8,'Agência número 8 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,9,'Agência número 9 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,10,'Agência número 10 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,11,'Agência número 11 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,12,'Agência número 12 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,13,'Agência número 13 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,14,'Agência número 14 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,15,'Agência número 15 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,16,'Agência número 16 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,17,'Agência número 17 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,18,'Agência número 18 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,19,'Agência número 19 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,20,'Agência número 20 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,21,'Agência número 21 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,22,'Agência número 22 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,23,'Agência número 23 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,24,'Agência número 24 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,25,'Agência número 25 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,26,'Agência número 26 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,27,'Agência número 27 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,28,'Agência número 28 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,29,'Agência número 29 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,30,'Agência número 30 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,31,'Agência número 31 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,32,'Agência número 32 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,33,'Agência número 33 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,34,'Agência número 34 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,35,'Agência número 35 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,36,'Agência número 36 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,37,'Agência número 37 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,38,'Agência número 38 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,39,'Agência número 39 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,40,'Agência número 40 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,41,'Agência número 41 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,42,'Agência número 42 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,43,'Agência número 43 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,44,'Agência número 44 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,45,'Agência número 45 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,46,'Agência número 46 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,47,'Agência número 47 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,48,'Agência número 48 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,49,'Agência número 49 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (1,50,'Agência número 50 do banco Banco do Brasil S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,1,'Agência número 1 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,2,'Agência número 2 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,3,'Agência número 3 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,4,'Agência número 4 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,5,'Agência número 5 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,6,'Agência número 6 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,7,'Agência número 7 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,8,'Agência número 8 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,9,'Agência número 9 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,10,'Agência número 10 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,11,'Agência número 11 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,12,'Agência número 12 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,13,'Agência número 13 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,14,'Agência número 14 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,15,'Agência número 15 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,16,'Agência número 16 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,17,'Agência número 17 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,18,'Agência número 18 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,19,'Agência número 19 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,20,'Agência número 20 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,21,'Agência número 21 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,22,'Agência número 22 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,23,'Agência número 23 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,24,'Agência número 24 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,25,'Agência número 25 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,26,'Agência número 26 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,27,'Agência número 27 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,28,'Agência número 28 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,29,'Agência número 29 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,30,'Agência número 30 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,31,'Agência número 31 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,32,'Agência número 32 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,33,'Agência número 33 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,34,'Agência número 34 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (247,35,'Agência número 35 do banco Banco Itaú S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,1,'Agência número 1 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,2,'Agência número 2 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,3,'Agência número 3 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,4,'Agência número 4 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,5,'Agência número 5 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,6,'Agência número 6 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,7,'Agência número 7 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,8,'Agência número 8 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,9,'Agência número 9 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,10,'Agência número 10 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,11,'Agência número 11 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,12,'Agência número 12 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,13,'Agência número 13 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,14,'Agência número 14 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,15,'Agência número 15 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,16,'Agência número 16 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,17,'Agência número 17 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,18,'Agência número 18 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,19,'Agência número 19 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,20,'Agência número 20 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,21,'Agência número 21 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,22,'Agência número 22 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,23,'Agência número 23 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,24,'Agência número 24 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,25,'Agência número 25 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,26,'Agência número 26 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,27,'Agência número 27 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,28,'Agência número 28 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,29,'Agência número 29 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (237,30,'Agência número 30 do banco Banco Bradesco S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,1,'Agência número 1 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,2,'Agência número 2 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,3,'Agência número 3 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,4,'Agência número 4 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,5,'Agência número 5 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,6,'Agência número 6 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,7,'Agência número 7 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,8,'Agência número 8 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,9,'Agência número 9 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,10,'Agência número 10 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,11,'Agência número 11 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,12,'Agência número 12 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,13,'Agência número 13 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,14,'Agência número 14 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,15,'Agência número 15 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,16,'Agência número 16 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,17,'Agência número 17 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,18,'Agência número 18 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,19,'Agência número 19 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,20,'Agência número 20 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,21,'Agência número 21 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,22,'Agência número 22 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,23,'Agência número 23 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,24,'Agência número 24 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,25,'Agência número 25 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,26,'Agência número 26 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,27,'Agência número 27 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,28,'Agência número 28 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (33,29,'Agência número 29 do banco Banco Santander (Brasil) S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,1,'Agência número 1 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,2,'Agência número 2 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,3,'Agência número 3 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,4,'Agência número 4 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,5,'Agência número 5 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,6,'Agência número 6 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,7,'Agência número 7 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,8,'Agência número 8 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,9,'Agência número 9 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,10,'Agência número 10 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,11,'Agência número 11 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,12,'Agência número 12 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,13,'Agência número 13 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,14,'Agência número 14 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,15,'Agência número 15 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,16,'Agência número 16 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,17,'Agência número 17 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,18,'Agência número 18 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,19,'Agência número 19 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,20,'Agência número 20 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,21,'Agência número 21 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,22,'Agência número 22 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,23,'Agência número 23 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,24,'Agência número 24 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,25,'Agência número 25 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,26,'Agência número 26 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,27,'Agência número 27 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,28,'Agência número 28 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,29,'Agência número 29 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,30,'Agência número 30 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,31,'Agência número 31 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,32,'Agência número 32 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,33,'Agência número 33 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,34,'Agência número 34 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,35,'Agência número 35 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,36,'Agência número 36 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,37,'Agência número 37 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,38,'Agência número 38 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,39,'Agência número 39 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,40,'Agência número 40 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,41,'Agência número 41 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,42,'Agência número 42 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,43,'Agência número 43 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,44,'Agência número 44 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,45,'Agência número 45 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,46,'Agência número 46 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,47,'Agência número 47 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,48,'Agência número 48 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,49,'Agência número 49 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,50,'Agência número 50 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,51,'Agência número 51 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,52,'Agência número 52 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,53,'Agência número 53 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,54,'Agência número 54 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,55,'Agência número 55 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,56,'Agência número 56 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,57,'Agência número 57 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,58,'Agência número 58 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,59,'Agência número 59 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,60,'Agência número 60 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,61,'Agência número 61 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,62,'Agência número 62 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,63,'Agência número 63 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,64,'Agência número 64 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,65,'Agência número 65 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,66,'Agência número 66 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,67,'Agência número 67 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,68,'Agência número 68 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,69,'Agência número 69 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,70,'Agência número 70 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,71,'Agência número 71 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,72,'Agência número 72 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,73,'Agência número 73 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,74,'Agência número 74 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,75,'Agência número 75 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,76,'Agência número 76 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,77,'Agência número 77 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,78,'Agência número 78 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,79,'Agência número 79 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,80,'Agência número 80 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,81,'Agência número 81 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,82,'Agência número 82 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,83,'Agência número 83 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,84,'Agência número 84 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,85,'Agência número 85 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,86,'Agência número 86 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,87,'Agência número 87 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,88,'Agência número 88 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,89,'Agência número 89 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,90,'Agência número 90 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,91,'Agência número 91 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,92,'Agência número 92 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,93,'Agência número 93 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,94,'Agência número 94 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,95,'Agência número 95 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,96,'Agência número 96 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,97,'Agência número 97 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,98,'Agência número 98 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,99,'Agência número 99 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,100,'Agência número 100 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,101,'Agência número 101 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (104,102,'Agência número 102 do banco Caixa Econômica Federal');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,1,'Agência número 1 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,2,'Agência número 2 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,3,'Agência número 3 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,4,'Agência número 4 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,5,'Agência número 5 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,6,'Agência número 6 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,7,'Agência número 7 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,8,'Agência número 8 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,9,'Agência número 9 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,10,'Agência número 10 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,11,'Agência número 11 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,12,'Agência número 12 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,13,'Agência número 13 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,14,'Agência número 14 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,15,'Agência número 15 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,16,'Agência número 16 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,17,'Agência número 17 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,18,'Agência número 18 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,19,'Agência número 19 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,20,'Agência número 20 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,21,'Agência número 21 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (399,22,'Agência número 22 do banco HSBC Bank Brasil S.A. - Banco Múltiplo');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (623,1,'Agência número 1 do banco Banco Panamericano S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (623,2,'Agência número 2 do banco Banco Panamericano S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (623,3,'Agência número 3 do banco Banco Panamericano S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (623,4,'Agência número 4 do banco Banco Panamericano S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (623,5,'Agência número 5 do banco Banco Panamericano S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (655,1,'Agência número 1 do banco Banco Votorantim S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (655,2,'Agência número 2 do banco Banco Votorantim S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (655,3,'Agência número 3 do banco Banco Votorantim S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (655,4,'Agência número 4 do banco Banco Votorantim S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (655,5,'Agência número 5 do banco Banco Votorantim S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (655,6,'Agência número 6 do banco Banco Votorantim S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (655,7,'Agência número 7 do banco Banco Votorantim S.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,1,'Agência número 1 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,2,'Agência número 2 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,3,'Agência número 3 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,4,'Agência número 4 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,5,'Agência número 5 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,6,'Agência número 6 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,7,'Agência número 7 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,8,'Agência número 8 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,9,'Agência número 9 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,10,'Agência número 10 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,11,'Agência número 11 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,12,'Agência número 12 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,13,'Agência número 13 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,14,'Agência número 14 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,15,'Agência número 15 do banco Citibank N.A.');
INSERT INTO agencia (banco_numero, numero, nome) VALUES (477,16,'Agência número 16 do banco Citibank N.A.');
